# Generated by Django 2.0.3 on 2018-04-17 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battleships_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('state', models.CharField(default='sea', max_length=20)),
                ('set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cols', models.IntegerField(default=10)),
                ('num_rows', models.IntegerField(default=10)),
                ('player_turn', models.IntegerField(default=1)),
                ('p1_ship_count', models.IntegerField(default=0)),
                ('p2_ship_count', models.IntegerField(default=0)),
                ('max_ships', models.IntegerField(default=10)),
                ('ships_of_size_1', models.IntegerField(default=0)),
                ('ships_of_size_2', models.IntegerField(default=0)),
                ('ships_of_size_3', models.IntegerField(default=0)),
                ('ships_of_size_4', models.IntegerField(default=0)),
                ('ships_of_size_5', models.IntegerField(default=0)),
                ('p1_ready', models.BooleanField(default=False)),
                ('p2_ready', models.BooleanField(default=False)),
                ('last_fired', models.CharField(default='( , )-hit_or_miss', max_length=15)),
                ('winner', models.IntegerField(default=0)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipyard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Shipyard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_count', models.IntegerField(default=0)),
                ('sunk', models.BooleanField(default=False)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Shipyard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AddField(
            model_name='cell',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
